### ISSUE TITLE
Minecraft Server Ping API

### ISSUE THREAD

**Issue by BasToTheMax** [micro/services#357] opened 2022-01-26 08:23 UTC
This api checks if a Minecraft server is online or not

**Comment by asim** [comment] 2022-01-26 08:49
I can imagine writing a generic ping service unless minecraft has some specific protocol. Assuming there's a http endpoint?

**Comment by BasToTheMax** [comment] 2022-01-26 11:24
Minecraft uses TCP

**Comment by asim** [comment] 2022-01-27 09:59
Alright so let's say its a ping service that supports http and tcp

service Ping {
    Url(...)
    Tcp(...)
    Ip(...)
    // other protocols
    ...
    // ping on an interval
    Monitor(...)
}

Make sense?

**Comment by BasToTheMax** [comment] 2022-01-27 14:06
> Alright so let's say its a ping service that supports http and tcp
> 
> ```
> service Ping {
>     Url(...)
>     Tcp(...)
>     Ip(...)
>     // other protocols
>     ...
>     // ping on an interval
>     Monitor(...)
> }
> ```
> 
> Make sense?

Yeah. Exactly like that!

**Comment by asim** [comment] 2022-01-27 14:12
Any comments on pricing? Free for one off checks, paid monitoring?

**Comment by asim** [comment] 2022-02-14 14:09
https://github.com/micro/services/pull/372

No interval yet

**Comment by asim** [comment] 2022-02-14 14:09
Dupe of https://github.com/micro/services/issues/285

**Comment by asim** [comment] 2022-02-14 14:57
Actually. I'm going to add a separate minecraft service specifically for minecraft ping

**Comment by asim** [comment] 2022-02-14 15:46
https://m3o.com/minecraft

**Closed by asim** 2022-02-14 15:46 UTC
